### ISSUE TITLE
how to update panel?

### ISSUE THREAD

**Issue by ItsHarshXD** [skyportlabs/panel#114]
How can I update the panel using commands? and quick question:

How can I shut down panel/node only with command

**Comment by privt00** [comment]
it is up to you how you started your panel and node so we cant know how to stop is as everyone could havea other methode how they started it

**Comment by ItsHarshXD** [comment]
> it is up to you how you started your panel and node so we cant know how to stop is as everyone could havea other methode how they started it

i purely followed the docs of how to start using node .

**Comment by privt00** [comment]
then stop it by pressing CTRL + C
