### ISSUE TITLE
add a register system

### ISSUE THREAD

**Issue by Elias-Lindholm** [skyportlabs/panel#12]
wouldent it be great if it had both a panel and client instead of separated.

**Comment by kanetjuh** [comment]
> wouldent it be great if it had both a panel and client instead of separated.

Hey, currently there is already a part of "registering" implemented by doing `npm run createUser` and inside the admin/users page. Besides that, could you eleborate "client" more (like what YOU like to see? Feedback/input is always welcome 😀)
