### ISSUE TITLE
Nodes returns nothing.

### ISSUE THREAD

**Issue by intelijidea** [skyportlabs/panel#32]
At `/admin/instances` page, when creating new instance list of nodes show nothing.

Could be preoblem at reading list of nodes form database,
![code](https://github.com/skyportlabs/panel/assets/80817984/218fee8d-9e16-404f-aef8-3703ea5d6d0c)

**Comment by atqr1** [comment]
@privt00 have a look, for me it works fine

**Comment by privt00** [comment]
@meowsocute did you created a Node?

**Comment by privt00** [comment]
> <img alt="Screenshot 2024-07-09 at 13 20 12" width="1510" src="https://private-user-images.githubusercontent.com/119353097/346953458-bd21e016-68ee-48ba-b989-bea3c088ee00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjc5MzUsIm5iZiI6MTcyMDUyNzYzNSwicGF0aCI6Ii8xMTkzNTMwOTcvMzQ2OTUzNDU4LWJkMjFlMDE2LTY4ZWUtNDhiYS1iOTg5LWJlYTNjMDg4ZWUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjIwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTIyNTY0YjhlMzM4MjM5OGMzOWI2NjkwMGE2Y2FmMGI1MTg1MDY1ZWRkZjcyZThhNDM2ZDg4Y2RhYjZhMGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eUa9ILIQ0lUXXJbB7FKYivwJbh3QFYhP-RlpIDle8EU">

Yeah its working need to be a error on his side. Maybe he forgot to add tags

**Comment by intelijidea** [comment]
Could be, thanks for reaching out!
