### ISSUE TITLE
First theme for a new panel?

### ISSUE THREAD

**Issue by AvexXS** [skyportlabs/panel#44]
What if i make the first ever skyport theme, i will not remove the Skyport Copyright credits but also add my own credits

Sounds good?
then you could make a themes repo where u add them all

**Comment by atqr1** [comment]
this isn't a very good time to do it, we are only 5 betas in

**Comment by atqr1** [comment]
also sure but don't ask us
skyport is MIT licensed, anyone can do anything

**Comment by privt00** [comment]
Credits Removal isnt allowed

**Comment by KingTino104** [comment]
> Credits Removal isnt allowed

did u not read what he said, he (@atqr1) said "skyport is MIT licensed, **anyone can do anything**"

**Comment by privt00** [comment]
Opensource dont means that you can just put an other License in or something. It always needs to Stay Opensource and you need to leave the credits. https://opensource.com/

**Comment by GraceskAxel** [comment]
Well, it dosen't matters if it's under MIT License or any other, credit removal is illegal and might even go to DMCA.

**Comment by privt00** [comment]
Right

**Comment by GraceskAxel** [comment]
Btw what if I create the second theme for Skyport.

**Comment by GraceskAxel** [comment]
@AvexXS want to create the first ever theme of Skyport together?

**Comment by privt00** [comment]
maybe you also could make a theme selector if you want

**Comment by GraceskAxel** [comment]
Yeah

**Comment by GraceskAxel** [comment]
I mean, I don't know why I'm asking Avex about working together here instead I can ask him in discord directly lmao.

**Comment by GraceskAxel** [comment]
> maybe you also could make a theme selector if you want

Maybe like the following:

Sky Theme ----> Pure Dark Theme -----> White Theme (NO SHIT)

**Comment by GraceskAxel** [comment]
> > maybe you also could make a theme selector if you want
> 
> Maybe like the following:
> 
> Sky Theme ----> Pure Dark Theme -----> White Theme (NO SHIT)

If we / I design white theme, while designing it, I'll or / we will die.

**Comment by GraceskAxel** [comment]
@privt00 are you gonna continue TFC?

**Comment by privt00** [comment]
im making it a billing addon for skyport

**Comment by privt00** [comment]
![grafik](https://github.com/user-attachments/assets/77bdf2d2-9dc8-4e89-9c63-4a96642bb8f0)
![grafik](https://github.com/user-attachments/assets/793ae023-7432-4f71-b748-cda1cf07b5f9)

**Comment by GraceskAxel** [comment]
oh, nice.

**Comment by privt00** [comment]
why? in the addon you dont need a seperat website for it

**Comment by GraceskAxel** [comment]
> why? in the addon you dont need a seperat website for it

oh.

**Comment by SamCoThePuggo** [comment]
Issue closed due to being de-railed into a general discussion.

**Comment by GraceskAxel** [comment]
It isn't closed yet.

**Comment by GraceskAxel** [comment]
There's more left.

**Comment by GraceskAxel** [comment]
I need to kick someone's ass.
