### ISSUE TITLE
Change authentication on Daemon to custom middleware

### ISSUE THREAD

**Issue by atqr1** [skyportlabs/panel#5]
Currently we use express basic auth, it's probably secure enough but by the time we begin preview releases it would be a good idea to swap it out

Self explanatory

note: for skyportd but I'm putting this here so more people see it and might want to deal with it for me

**Comment by blueiicey** [comment]
I am not a cucumber!!!

**Comment by privt00** [comment]
you are 100% a cucumber!!

**Comment by blueiicey** [comment]
no i am NOT!!!

**Comment by blueiicey** [comment]
your the cucumber here

**Comment by blueiicey** [comment]
privt is a non-sigma!!!!

**Comment by blueiicey** [comment]
skill issue

**Comment by blueiicey** [comment]
error moment 💀

**Comment by blueiicey** [comment]
**### _# privt is a monkey_**

**Comment by blueiicey** [comment]
### I AM NOT A CUCUMBER, RUS IS LYING!!

**Comment by blueiicey** [comment]
pls no ban 😭 😭

**Comment by blueiicey** [comment]
### FREE ROBUX!!!!!!!!!!!!!!!!!!!!

**Comment by blueiicey** [comment]
**### _# narrr_**
