### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by rechanting** [skyportlabs/panel#9]
Hello! I was looking at panels and then I found this one, amazing work so far! I just got 2 quick questions,

1. would it be possible to add a migration system from pterodactyl to skyport?

2. I am a beginner programmer and looking for projects to contribute to, can I contribute to this in some way?

**Comment by atqr1** [comment]
Hi, thanks for using Skyport

1. I'm really not sure, Pterodactyl uses a very different db structure but it might be possible eventually
2. You can join our discord: https://discord.gg/RJYpGa74RJ - I'll have a list of unfinished / need to be done features in #discussion soon

**Comment by arkseek** [comment]
Hey, and of course! hopefully it might be able to and sure let me join
